import { ButtonTheme } from "./types";

export const themeConfig = {
  [ButtonTheme.PRIMARY]: {
    lightBackground: "bg-primary-300",
    lightText: "text-primary-300",
    lightBorder: "border-primary-300",
    lightBackgroundOnHover: "hover:bg-primary-300",
    mediumBackground: "bg-primary",
    mediumText: "text-primary",
    mediumBorder: "border-primary",
    mediumBackgroundOnHover: "hover:bg-primary",
    boldBackgroundOnHover: "hover:bg-primary-700",
  },
  [ButtonTheme.SUCCESS]: {
    lightBackground: "bg-[#28ea8c]",
    lightText: "text-[#28ea8c]",
    lightBorder: "border-[#28ea8c]",
    lightBackgroundOnHover: "hover:bg-[#28ea8c]",
    mediumBackground: "bg-[#0f9d58]",
    mediumText: "text-[#0f9d58]",
    mediumBorder: "border-[#0f9d58]",
    mediumBackgroundOnHover: "hover:bg-[#0f9d58]",
    boldBackgroundOnHover: "hover:bg-[#008444]",
  },
  [ButtonTheme.WARNING]: {
    lightBackground: "bg-[#ffd45b]",
    lightText: "text-[#ffd45b]",
    lightBorder: "border-[#ffd45b]",
    lightBackgroundOnHover: "hover:bg-[#ffd45b]",
    mediumBackground: "bg-[#F4B400]",
    mediumText: "text-[#F4B400]",
    mediumBorder: "border-[#F4B400]",
    mediumBackgroundOnHover: "hover:bg-[#F4B400]",
    boldBackgroundOnHover: "hover:bg-[#a17700]",
  },
  [ButtonTheme.DANGER]: {
    lightBackground: "bg-[#eb958d]",
    lightText: "text-[#eb958d]",
    lightBorder: "border-[#eb958d]",
    lightBackgroundOnHover: "hover:bg-[#eb958d]",
    mediumBackground: "bg-[#db4437]",
    mediumText: "text-[#db4437]",
    mediumBorder: "border-[#db4437]",
    mediumBackgroundOnHover: "hover:bg-[#db4437]",
    boldBackgroundOnHover: "hover:bg-[#b3170a]",
  },
  [ButtonTheme.SECONDARY]: {
    lightBackground: "bg-secondary-300",
    lightText: "text-secondary-300",
    lightBorder: "border-secondary-300",
    lightBackgroundOnHover: "hover:bg-secondary-300",
    mediumBackground: "bg-secondary",
    mediumText: "text-secondary",
    mediumBorder: "border-secondary",
    mediumBackgroundOnHover: "hover:bg-secondary",
    boldBackgroundOnHover: "hover:bg-secondary-700",
  },
};
