/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as TermsIndexRouteImport } from "./routes/terms/index";
import { Route as SignupIndexRouteImport } from "./routes/signup/index";
import { Route as ProfileIndexRouteImport } from "./routes/profile/index";
import { Route as PrivacyIndexRouteImport } from "./routes/privacy/index";
import { Route as LoginIndexRouteImport } from "./routes/login/index";
import { Route as DashboardIndexRouteImport } from "./routes/dashboard/index";
import { Route as AboutIndexRouteImport } from "./routes/about/index";

const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const TermsIndexRoute = TermsIndexRouteImport.update({
  id: "/terms/",
  path: "/terms/",
  getParentRoute: () => rootRouteImport,
} as any);
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: "/signup/",
  path: "/signup/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: "/profile/",
  path: "/profile/",
  getParentRoute: () => rootRouteImport,
} as any);
const PrivacyIndexRoute = PrivacyIndexRouteImport.update({
  id: "/privacy/",
  path: "/privacy/",
  getParentRoute: () => rootRouteImport,
} as any);
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: "/login/",
  path: "/login/",
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: "/dashboard/",
  path: "/dashboard/",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutIndexRoute = AboutIndexRouteImport.update({
  id: "/about/",
  path: "/about/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/login": typeof LoginIndexRoute;
  "/privacy": typeof PrivacyIndexRoute;
  "/profile": typeof ProfileIndexRoute;
  "/signup": typeof SignupIndexRoute;
  "/terms": typeof TermsIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutIndexRoute;
  "/dashboard": typeof DashboardIndexRoute;
  "/login": typeof LoginIndexRoute;
  "/privacy": typeof PrivacyIndexRoute;
  "/profile": typeof ProfileIndexRoute;
  "/signup": typeof SignupIndexRoute;
  "/terms": typeof TermsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about/": typeof AboutIndexRoute;
  "/dashboard/": typeof DashboardIndexRoute;
  "/login/": typeof LoginIndexRoute;
  "/privacy/": typeof PrivacyIndexRoute;
  "/profile/": typeof ProfileIndexRoute;
  "/signup/": typeof SignupIndexRoute;
  "/terms/": typeof TermsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/about"
    | "/dashboard"
    | "/login"
    | "/privacy"
    | "/profile"
    | "/signup"
    | "/terms";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/about"
    | "/dashboard"
    | "/login"
    | "/privacy"
    | "/profile"
    | "/signup"
    | "/terms";
  id:
    | "__root__"
    | "/"
    | "/about/"
    | "/dashboard/"
    | "/login/"
    | "/privacy/"
    | "/profile/"
    | "/signup/"
    | "/terms/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutIndexRoute: typeof AboutIndexRoute;
  DashboardIndexRoute: typeof DashboardIndexRoute;
  LoginIndexRoute: typeof LoginIndexRoute;
  PrivacyIndexRoute: typeof PrivacyIndexRoute;
  ProfileIndexRoute: typeof ProfileIndexRoute;
  SignupIndexRoute: typeof SignupIndexRoute;
  TermsIndexRoute: typeof TermsIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/terms/": {
      id: "/terms/";
      path: "/terms";
      fullPath: "/terms";
      preLoaderRoute: typeof TermsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/signup/": {
      id: "/signup/";
      path: "/signup";
      fullPath: "/signup";
      preLoaderRoute: typeof SignupIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/profile/": {
      id: "/profile/";
      path: "/profile";
      fullPath: "/profile";
      preLoaderRoute: typeof ProfileIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/privacy/": {
      id: "/privacy/";
      path: "/privacy";
      fullPath: "/privacy";
      preLoaderRoute: typeof PrivacyIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/login/": {
      id: "/login/";
      path: "/login";
      fullPath: "/login";
      preLoaderRoute: typeof LoginIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/dashboard/": {
      id: "/dashboard/";
      path: "/dashboard";
      fullPath: "/dashboard";
      preLoaderRoute: typeof DashboardIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about/": {
      id: "/about/";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutIndexRoute: AboutIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  PrivacyIndexRoute: PrivacyIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  TermsIndexRoute: TermsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
